### ISSUE TITLE
Mate, you're a champ

### ISSUE THREAD

**Issue by cyruseuros** [alphapapa/defrepeater.el#4]
Feel free to delete the issue as unproductive. Just wanted to say you made my day.

Also the people that told you hydra does the same are missing the point. Hydra is great, but for me (and I'm guessing a lot of other users), it's waaaay too much overhead for 80% of it's use-cases.

Congratulations on having the clarity of mind to notice and do something about it.

**Comment by alphapapa** [comment]
Thanks for the kind words.  Glad it's useful to you.
